# Generated by Django 4.2.20 on 2025-12-02 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightlogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flightlog',
            options={'ordering': ['-flight_date']},
        ),
        migrations.AlterModelTable(
            name='flightlog',
            table='flightplan_flightlog',
        ),
    ]
