# money/forms/events/events.py

from __future__ import annotations

from django import forms
from django.utils import timezone
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Column, Layout, Row, Submit, HTML

from money.models import Client, Event


def year_choices(start: int = 2020, years_ahead: int = 2):
    current = timezone.localdate().year
    return [(y, str(y)) for y in range(start, current + years_ahead + 1)]


class _BaseEventForm(forms.ModelForm):
    """
    Shared behavior for create + update:
    - scopes client dropdown by user
    - sets instance.user before model validation
    - defaults year and type for new objects
    """

    class Meta:
        model = Event
        fields = [
            "title",
            "client",
            "event_year",
            "event_type",
            "location_city",
            "location_address",
            "notes",
        ]
        widgets = {
            "title": forms.TextInput(attrs={"class": "form-control"}),
            "client": forms.Select(attrs={"class": "form-select"}),
            "event_year": forms.Select(attrs={"class": "form-select"}),
            "event_type": forms.Select(attrs={"class": "form-select"}),
            "location_city": forms.TextInput(attrs={"class": "form-control"}),
            "location_address": forms.TextInput(attrs={"class": "form-control"}),
            "notes": forms.Textarea(attrs={"rows": 3, "class": "form-control"}),
        }

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)

        # Ensure owner is set BEFORE full_clean (OwnedModelMixin.clean)
        if self.user is not None and getattr(self.instance, "user_id", None) is None:
            self.instance.user = self.user

        # Dynamic year choices + sensible create default
        self.fields["event_year"].choices = year_choices()
        if not self.instance.pk and not self.initial.get("event_year"):
            self.initial["event_year"] = timezone.localdate().year

        # Default to commercial (race folded into commercial)
        if not self.instance.pk and not self.initial.get("event_type"):
            self.initial["event_type"] = "commercial"

        # Scope client dropdown
        if self.user is not None:
            self.fields["client"].queryset = Client.objects.filter(user=self.user).order_by(
                "business", "last", "first"
            )
        else:
            self.fields["client"].queryset = Client.objects.none()
        self.fields["client"].required = False

        # Crispy shared layout pieces will be assembled in subclasses
        self.helper = FormHelper()
        self.helper.form_method = "post"
        self.helper.label_class = "fw-semibold"

    def clean(self):
        cleaned = super().clean()
        for f in ("title", "location_city", "location_address"):
            if cleaned.get(f):
                cleaned[f] = cleaned[f].strip()
        if cleaned.get("notes"):
            cleaned["notes"] = cleaned["notes"].strip()
        return cleaned


class EventCreateForm(_BaseEventForm):
    """
    Create-only: includes optional job_number override.
    """

    job_number = forms.CharField(
        required=False,
        label="Job Number (optional override)",
        help_text="Leave blank to auto-generate. Base number only (example: 261000).",
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "Auto (optional override)",
                "inputmode": "numeric",
                "autocomplete": "off",
            }
        ),
    )

    class Meta(_BaseEventForm.Meta):
        fields = _BaseEventForm.Meta.fields + ["job_number"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper.layout = Layout(
            Row(
                Column("title", css_class="col-12 col-md-6"),
                Column("client", css_class="col-12 col-md-6"),
            ),
            Row(
                Column("event_type", css_class="col-12 col-md-4"),
                Column("event_year", css_class="col-12 col-md-4"),
                Column("location_city", css_class="col-12 col-md-4"),
            ),
            Row(Column("location_address", css_class="col-12")),
            Row(
                Column("job_number", css_class="col-12 col-md-4"),
                Column(
                    HTML(
                        '<div class="form-text text-muted mt-2">'
                        "Auto-generated by year/type segment. You can override once at creation."
                        "</div>"
                    ),
                    css_class="col-12 col-md-8",
                ),
            ),
            Row(Column("notes", css_class="col-12")),
            Submit("submit", "Save Changes", css_class="btn btn-primary float-end"),

        )

    def clean_job_number(self):
        val = (self.cleaned_data.get("job_number") or "").strip()
        return val or None

    def clean(self):
        cleaned = super().clean()

        # Push override onto instance so Event.clean() validates it before save()
        jobnum = cleaned.get("job_number")
        if jobnum:
            self.instance.job_number = jobnum

        return cleaned


class EventUpdateForm(_BaseEventForm):
    """
    Update-only: job_number is locked and not shown.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper.layout = Layout(
            Row(
                Column("title", css_class="col-12 col-md-6"),
                Column("client", css_class="col-12 col-md-6"),
            ),
            Row(
                Column("event_type", css_class="col-12 col-md-4"),
                Column("event_year", css_class="col-12 col-md-4"),
                Column("location_city", css_class="col-12 col-md-4"),
            ),
            Row(Column("location_address", css_class="col-12")),
            Row(Column("notes", css_class="col-12")),
            Submit("submit", "Save Changes", css_class="btn btn-primary float-end"),

        )
