# Generated by Django 4.2.20 on 2025-11-20 02:43

from django.conf import settings
import django.contrib.postgres.search
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import money.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=500, null=True)),
                ('schedule_c_line', models.CharField(blank=True, help_text="Enter Schedule C line number (e.g., '8', '9', '27a')", max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.CharField(blank=True, max_length=500, null=True)),
                ('first', models.CharField(blank=True, max_length=500, null=True)),
                ('last', models.CharField(blank=True, max_length=500, null=True)),
                ('street', models.CharField(blank=True, max_length=500, null=True)),
                ('address2', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Short identifier for this client (e.g., 'airborne-images', 'skyguy').", unique=True)),
                ('legal_name', models.CharField(help_text='Registered legal name used on invoices.', max_length=255)),
                ('display_name', models.CharField(blank=True, help_text='Public/trade name; falls back to legal name if blank.', max_length=255)),
                ('logo', models.ImageField(help_text='Primary logo used in invoice header.', upload_to=money.models.logo_upload_path, validators=[money.models.validate_image_extension_no_svg])),
                ('logo_light', models.ImageField(blank=True, help_text='Optional light-mode logo variation.', null=True, upload_to=money.models.logo_upload_path, validators=[money.models.validate_image_extension_no_svg])),
                ('logo_dark', models.ImageField(blank=True, help_text='Optional dark-mode logo variation.', null=True, upload_to=money.models.logo_upload_path, validators=[money.models.validate_image_extension_no_svg])),
                ('logo_alt_text', models.CharField(blank=True, help_text='Accessible alt text for the logo image.', max_length=255)),
                ('brand_color_primary', models.CharField(blank=True, help_text='Primary brand color (hex), e.g., #0055FF.', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color like #000000 or #fff.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('brand_color_secondary', models.CharField(blank=True, help_text='Secondary brand color (hex), optional.', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color like #000000 or #fff.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('website', models.URLField(blank=True)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state_province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='United States', max_length=100)),
                ('main_phone', models.CharField(blank=True, max_length=50)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('invoice_reply_to_email', models.EmailField(blank=True, max_length=254)),
                ('billing_contact_name', models.CharField(blank=True, max_length=255)),
                ('billing_contact_email', models.EmailField(blank=True, max_length=254)),
                ('tax_id_ein', models.CharField(blank=True, help_text='EIN / Tax ID as displayed on invoices (do not include sensitive PII).', max_length=64)),
                ('pay_to_name', models.CharField(blank=True, help_text='Name checks should be made payable to (defaults to legal_name if blank).', max_length=255)),
                ('remittance_address', models.TextField(blank=True, help_text='If different from primary address. Multiline allowed.')),
                ('default_terms', models.CharField(blank=True, help_text='e.g., "Net 30".', max_length=100)),
                ('default_net_days', models.PositiveIntegerField(default=30)),
                ('default_late_fee_policy', models.CharField(blank=True, help_text='Short line like "1.5% per month after 30 days".', max_length=255)),
                ('default_footer_text', models.TextField(blank=True, help_text='Footer / legal disclaimers displayed on invoices.')),
                ('pdf_header_layout', models.CharField(choices=[('stacked', 'Stacked (logo above address)'), ('inline-left', 'Inline (logo left, address right)'), ('inline-right', 'Inline (address left, logo right)')], default='inline-left', max_length=20)),
                ('header_logo_max_width_px', models.PositiveIntegerField(default=320, help_text='Render hint for PDF header logo max width.')),
                ('default_currency', models.CharField(default='USD', max_length=3)),
                ('default_locale', models.CharField(default='en_US', max_length=10)),
                ('timezone', models.CharField(default='America/Indiana/Indianapolis', max_length=64)),
                ('is_active', models.BooleanField(default=False, help_text='Only one active profile allowed per deployment.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('race', 'Race'), ('event', 'Event'), ('other', 'Other')], default='race', max_length=50)),
                ('location_city', models.CharField(blank=True, max_length=200, null=True)),
                ('location_address', models.CharField(blank=True, max_length=500, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=25, null=True)),
                ('event_name', models.CharField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12)),
                ('date', models.DateField()),
                ('due', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Partial', 'Partial')], default='Unpaid', max_length=20)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('from_name', models.CharField(blank=True, max_length=255)),
                ('from_address', models.TextField(blank=True)),
                ('from_phone', models.CharField(blank=True, max_length=50)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('from_website', models.URLField(blank=True)),
                ('from_tax_id', models.CharField(blank=True, max_length=64)),
                ('from_logo_url', models.URLField(blank=True)),
                ('from_header_logo_max_width_px', models.PositiveIntegerField(default=320)),
                ('from_terms', models.CharField(blank=True, max_length=100)),
                ('from_net_days', models.PositiveIntegerField(default=30)),
                ('from_footer_text', models.TextField(blank=True)),
                ('from_currency', models.CharField(default='USD', max_length=3)),
                ('from_locale', models.CharField(default='en_US', max_length=10)),
                ('from_timezone', models.CharField(default='America/Indiana/Indianapolis', max_length=64)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('pdf_url', models.URLField(blank=True)),
                ('pdf_sha256', models.CharField(blank=True, max_length=64)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='money.client')),
                ('event', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='money.event')),
            ],
            options={
                'ordering': ['invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='MileageRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, default=0.7, max_digits=5)),
            ],
            options={
                'verbose_name': 'Mileage Rate',
                'verbose_name_plural': 'Mileage Rates',
            },
        ),
        migrations.CreateModel(
            name='RecurringTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], default='Expense', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('transaction', models.CharField(max_length=255)),
                ('day', models.IntegerField(help_text='Day of the month to apply')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('active', models.BooleanField(default=True)),
                ('last_created', models.DateField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, help_text='Auto-filled from Sub-Category.', null=True, on_delete=django.db.models.deletion.PROTECT, to='money.category')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='money.event')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_cat', models.CharField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('schedule_c_line', models.CharField(blank=True, help_text='Enter Schedule C line number.', max_length=10, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='money.category')),
            ],
            options={
                'verbose_name_plural': 'Sub Categories',
                'ordering': ['sub_cat'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], default='Expense', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('transaction', models.CharField(max_length=255)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('date', models.DateField()),
                ('invoice_number', models.CharField(blank=True, help_text='Optional', max_length=25, null=True)),
                ('transport_type', models.CharField(blank=True, choices=[('personal_vehicle', 'Personal Vehicle'), ('rental_car', 'Rental Car')], help_text='Used to identify if actual expenses apply', max_length=30, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='money.category')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='money.event')),
                ('recurring_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_transactions', to='money.recurringtransaction')),
                ('sub_cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='money.subcategory')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='money.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='sub_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='money.subcategory'),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='money.team'),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=255, null=True)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='money.event')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='money.transaction')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Miles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('begin', models.DecimalField(decimal_places=1, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('end', models.DecimalField(decimal_places=1, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('total', models.DecimalField(decimal_places=1, editable=False, max_digits=10, null=True)),
                ('invoice_number', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('vehicle', models.CharField(default='Lead Foot', max_length=255, null=True)),
                ('mileage_type', models.CharField(choices=[('Taxable', 'Taxable'), ('Reimbursed', 'Reimbursed')], default='Taxable', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='money.client')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='money.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Miles',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('qty', models.IntegerField(blank=True, default=0, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='money.invoice')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='money.service'),
        ),
        migrations.AddConstraint(
            model_name='clientprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_client_profile'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date', 'trans_type'], name='money_trans_date_fbbc99_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'date'], name='money_trans_user_id_476296_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['event'], name='money_trans_event_i_f9d321_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category'], name='money_trans_categor_3538f4_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['sub_cat'], name='money_trans_sub_cat_c36845_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['invoice_number'], name='money_trans_invoice_d1f344_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['user', 'day', 'active'], name='money_recur_user_id_7ced44_idx'),
        ),
        migrations.AddIndex(
            model_name='miles',
            index=models.Index(fields=['user', 'date'], name='money_miles_user_id_1f690c_idx'),
        ),
        migrations.AddIndex(
            model_name='miles',
            index=models.Index(fields=['mileage_type'], name='money_miles_mileage_8e62c1_idx'),
        ),
    ]
