# Generated by Django 4.2.20 on 2025-11-26 23:59

from decimal import Decimal
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, help_text='Human-visible invoice ID (unique per client).', max_length=25, null=True)),
                ('event_name', models.CharField(blank=True, help_text='Display name of the event at time of invoicing.', max_length=500, null=True)),
                ('location', models.CharField(blank=True, help_text='Display location (city/track) at time of invoicing.', max_length=500, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Total invoice amount, calculated from line items.', max_digits=12)),
                ('date', models.DateField(help_text='Invoice date.')),
                ('due', models.DateField(help_text='Due date.')),
                ('paid_date', models.DateField(blank=True, help_text='Date fully paid.', null=True)),
                ('status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Partial', 'Partial')], default='Unpaid', max_length=20)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('from_name', models.CharField(blank=True, help_text='Business name as shown on this invoice.', max_length=255)),
                ('from_address', models.TextField(blank=True, help_text='Postal address block as printed on this invoice.')),
                ('from_phone', models.CharField(blank=True, max_length=50)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('from_website', models.URLField(blank=True)),
                ('from_tax_id', models.CharField(blank=True, help_text='Tax ID / EIN as shown on this invoice.', max_length=64)),
                ('from_logo_url', models.URLField(blank=True, help_text='Absolute or storage URL to logo used on this invoice.')),
                ('from_header_logo_max_width_px', models.PositiveIntegerField(default=320)),
                ('from_terms', models.CharField(blank=True, help_text='e.g., "Net 30".', max_length=100)),
                ('from_net_days', models.PositiveIntegerField(default=30, help_text='Number of days from invoice date to due date when issued.')),
                ('from_footer_text', models.TextField(blank=True, help_text='Footer notes / payment instructions as shown on this invoice.')),
                ('from_currency', models.CharField(default='USD', help_text='ISO currency code captured at issue time.', max_length=3)),
                ('from_locale', models.CharField(default='en_US', max_length=10)),
                ('from_timezone', models.CharField(default='America/Indiana/Indianapolis', max_length=64)),
                ('issued_at', models.DateTimeField(blank=True, help_text='Set when the invoice is officially issued/sent.', null=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Revision number; bump when you create a new version.')),
                ('pdf_url', models.URLField(blank=True, help_text='Location of the archived PDF (e.g., S3).')),
                ('pdf_sha256', models.CharField(blank=True, help_text='Optional SHA-256 hash of the archived PDF for integrity checks.', max_length=64)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices_v2', to='money.client')),
                ('event', models.ForeignKey(blank=True, help_text='Optional: link this invoice to a specific event/race.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices_v2', to='money.event')),
                ('service', models.ForeignKey(help_text='Primary service for this invoice (e.g., FPV, broadcast, etc.).', on_delete=django.db.models.deletion.PROTECT, related_name='invoices_v2', to='money.service')),
            ],
            options={
                'ordering': ['invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItemV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('qty', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Quantity (hours, days, units, etc.).', max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Unit price.', max_digits=10)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items_v2', to='money.category')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='money.invoicev2')),
                ('sub_cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items_v2', to='money.subcategory')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddIndex(
            model_name='invoicev2',
            index=models.Index(fields=['invoice_number'], name='money_invoi_invoice_f06be6_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicev2',
            index=models.Index(fields=['client', 'date'], name='money_invoi_client__a190eb_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicev2',
            index=models.Index(fields=['event', 'date'], name='money_invoi_event_i_e8d0c8_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicev2',
            index=models.Index(fields=['status'], name='money_invoi_status_98844a_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoicev2',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice_number__isnull', False)), fields=('client', 'invoice_number'), name='uniq_invoicev2_per_client'),
        ),
    ]
