# Generated by Django 4.2.20 on 2025-11-27 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_invoicev2_invoiceitemv2_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoicev2',
            name='uniq_invoicev2_per_client',
        ),
        migrations.AlterField(
            model_name='invoiceitemv2',
            name='category',
            field=models.ForeignKey(blank=True, editable=False, help_text='Set automatically from sub-category.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items_v2', to='money.category'),
        ),
        migrations.AlterField(
            model_name='invoiceitemv2',
            name='sub_cat',
            field=models.ForeignKey(blank=True, help_text='Choose the sub-category; category will be set automatically.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items_v2', to='money.subcategory'),
        ),
        migrations.AlterField(
            model_name='invoicev2',
            name='from_timezone',
            field=models.CharField(default='America/Indiana/Indiana polis', max_length=64),
        ),
        migrations.AlterField(
            model_name='invoicev2',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Human-visible invoice ID (YYNNNN format; auto-generated if blank).', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='invoicev2',
            name='service',
            field=models.ForeignKey(help_text='Primary service for this invoice.', on_delete=django.db.models.deletion.PROTECT, related_name='invoices_v2', to='money.service'),
        ),
        migrations.AddConstraint(
            model_name='invoicev2',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice_number__isnull', False)), fields=('invoice_number',), name='uniq_invoicev2_number'),
        ),
    ]
