# Generated by Django 4.2.20 on 2025-11-28 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('money', '0003_remove_invoicev2_uniq_invoicev2_per_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicev2',
            name='sent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when this invoice email was last sent.', null=True),
        ),
        migrations.AddField(
            model_name='invoicev2',
            name='sent_by',
            field=models.ForeignKey(blank=True, help_text='User who last sent this invoice.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_v2_emails_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoicev2',
            name='sent_to',
            field=models.EmailField(blank=True, help_text='Email address the invoice was last sent to.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='invoicev2',
            name='from_timezone',
            field=models.CharField(default='America/Indiana/Indianapolis', max_length=64),
        ),
    ]
