# Generated by Django 4.2.20 on 2025-11-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0004_invoicev2_sent_at_invoicev2_sent_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicev2',
            name='pdf_snapshot',
            field=models.FileField(blank=True, help_text='Archived PDF snapshot stored in default storage.', null=True, upload_to='invoices_v2/'),
        ),
        migrations.AddField(
            model_name='invoicev2',
            name='pdf_snapshot_created_at',
            field=models.DateTimeField(blank=True, help_text='When the snapshot was generated.', null=True),
        ),
    ]
