# Generated by Django 4.2.20 on 2025-11-28 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0005_invoicev2_pdf_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miles',
            name='invoice_v2',
            field=models.ForeignKey(blank=True, help_text='If set, this mileage entry is tied to an Invoice V2.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mileage_entries', to='money.invoicev2'),
        ),
        migrations.AlterField(
            model_name='miles',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Event this mileage was associated with (for event-level cost analysis).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='money.event'),
        ),
        migrations.AlterField(
            model_name='miles',
            name='invoice_number',
            field=models.CharField(blank=True, db_index=True, help_text='Legacy invoice number string. For new entries, usually mirrors InvoiceV2.invoice_number.', max_length=255, null=True),
        ),
    ]
