# Generated by Django 4.2.20 on 2025-12-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0006_miles_invoice_v2_alter_miles_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='pdf_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='invoicev2',
            name='pdf_url',
            field=models.URLField(blank=True, help_text='Location of the archived PDF (e.g., S3).', max_length=1000),
        ),
    ]
