# Generated by Django 4.2.20 on 2025-12-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0007_alter_invoice_pdf_url_alter_invoicev2_pdf_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], default='Expense', help_text='Default accounting nature for this category.', max_length=10),
        ),
    ]
