# Generated by Django 4.2.20 on 2025-12-18 03:29

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('money', '0008_category_category_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mileagerate',
            options={'ordering': ['-year'], 'verbose_name': 'Mileage Rate', 'verbose_name_plural': 'Mileage Rates'},
        ),
        migrations.AddField(
            model_name='mileagerate',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Optional: set per-user rates. Leave blank for a global rate.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mileagerate',
            name='year',
            field=models.PositiveIntegerField(db_index=True, default=2025),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mileagerate',
            name='rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.7000'), help_text='Dollars per mile for this year (e.g. 0.6700).', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddConstraint(
            model_name='mileagerate',
            constraint=models.UniqueConstraint(fields=('user', 'year'), name='uniq_mileage_rate_user_year'),
        ),
    ]
