# Generated by Django 4.2.20 on 2025-12-30 00:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('money', '0009_alter_mileagerate_options_mileagerate_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('placed_in_service_date', models.DateField()),
                ('placed_in_service_mileage', models.DecimalField(decimal_places=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('year', models.PositiveIntegerField()),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('plate', models.CharField(blank=True, max_length=20, null=True)),
                ('vin', models.CharField(blank=True, max_length=17, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('expense_type', models.CharField(choices=[('Maintenance', 'Maintenance'), ('Repair', 'Repair'), ('Tires', 'Tires'), ('Fuel', 'Fuel'), ('Insurance', 'Insurance'), ('Registration', 'Registration'), ('Citation', 'Citation'), ('Equipment', 'Equipment'), ('Other', 'Other')], default='Other', max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('odometer', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='vehicle/receipts/')),
                ('is_tax_related', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='VehicleYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_year', models.PositiveIntegerField()),
                ('begin_mileage', models.DecimalField(decimal_places=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('end_mileage', models.DecimalField(decimal_places=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['-tax_year'],
            },
        ),
        migrations.AddIndex(
            model_name='miles',
            index=models.Index(fields=['vehicle'], name='money_miles_vehicle_fc6546_idx'),
        ),
        migrations.AddField(
            model_name='vehicleyear',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_records', to='money.vehicle'),
        ),
        migrations.AddField(
            model_name='vehicleexpense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicleexpense',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='money.vehicle'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='miles',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='money.vehicle'),
        ),
        migrations.AddIndex(
            model_name='vehicleyear',
            index=models.Index(fields=['tax_year'], name='money_vehic_tax_yea_2ff191_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vehicleyear',
            unique_together={('vehicle', 'tax_year')},
        ),
        migrations.AddIndex(
            model_name='vehicleexpense',
            index=models.Index(fields=['user', 'date'], name='money_vehic_user_id_5bf5ff_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleexpense',
            index=models.Index(fields=['vehicle', 'date'], name='money_vehic_vehicle_4e338d_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleexpense',
            index=models.Index(fields=['expense_type'], name='money_vehic_expense_fb8ac2_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['user', 'is_active'], name='money_vehic_user_id_69575c_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vin'], name='money_vehic_vin_e56e2a_idx'),
        ),
    ]
