# Generated by Django 4.2.20 on 2025-12-30 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0010_vehicle_vehicleexpense_vehicleyear_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehicleyear',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='mileagerate',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('year',), name='uniq_mileage_rate_global_year'),
        ),
        migrations.AddConstraint(
            model_name='vehicleyear',
            constraint=models.UniqueConstraint(fields=('vehicle', 'tax_year'), name='uniq_vehicle_year'),
        ),
    ]
