# Generated by Django 4.2.20 on 2025-12-31 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0011_alter_vehicleyear_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='include_in_tax_reports',
            field=models.BooleanField(default=True, help_text='If unchecked, this sub-category is excluded from tax-related reports.'),
        ),
        migrations.AlterField(
            model_name='miles',
            name='mileage_type',
            field=models.CharField(choices=[('Business', 'Business'), ('Commuting', 'Commuting'), ('Other', 'Other'), ('Reimbursed', 'Reimbursed')], default='Business', max_length=20),
        ),
    ]
