# Generated by Django 4.2.20 on 2025-12-31 01:13

import django.core.validators
from django.db import migrations, models
import money.models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0012_subcategory_include_in_tax_reports_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Short identifier for this client (e.g., 'airborne-images', 'skyguy').", unique=True)),
                ('legal_name', models.CharField(help_text='Registered legal name used on invoices.', max_length=255)),
                ('display_name', models.CharField(blank=True, help_text='Public/trade name; falls back to legal name if blank.', max_length=255)),
                ('logo', models.ImageField(help_text='Primary logo used in invoice header.', upload_to=money.models.logo_upload_path, validators=[money.models.validate_image_extension_no_svg])),
                ('logo_light', models.ImageField(blank=True, help_text='Optional light-mode logo variation.', null=True, upload_to=money.models.logo_upload_path, validators=[money.models.validate_image_extension_no_svg])),
                ('logo_dark', models.ImageField(blank=True, help_text='Optional dark-mode logo variation.', null=True, upload_to=money.models.logo_upload_path, validators=[money.models.validate_image_extension_no_svg])),
                ('logo_alt_text', models.CharField(blank=True, help_text='Accessible alt text for the logo image.', max_length=255)),
                ('brand_color_primary', models.CharField(blank=True, help_text='Primary brand color (hex), e.g., #0055FF.', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color like #000000 or #fff.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('brand_color_secondary', models.CharField(blank=True, help_text='Secondary brand color (hex), optional.', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color like #000000 or #fff.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('website', models.URLField(blank=True)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state_province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='United States', max_length=100)),
                ('main_phone', models.CharField(blank=True, max_length=50)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('invoice_reply_to_email', models.EmailField(blank=True, max_length=254)),
                ('billing_contact_name', models.CharField(blank=True, max_length=255)),
                ('billing_contact_email', models.EmailField(blank=True, max_length=254)),
                ('tax_id_ein', models.CharField(blank=True, help_text='EIN / Tax ID as displayed on invoices (do not include sensitive PII).', max_length=64)),
                ('vehicle_expense_method', models.CharField(choices=[('mileage', 'Standard mileage'), ('actual', 'Actual vehicle expenses')], default='mileage', help_text='Tax reporting method for vehicle costs.', max_length=20)),
                ('pay_to_name', models.CharField(blank=True, help_text='Name checks should be made payable to (defaults to legal_name if blank).', max_length=255)),
                ('remittance_address', models.TextField(blank=True, help_text='If different from primary address. Multiline allowed.')),
                ('default_terms', models.CharField(blank=True, help_text='e.g., "Net 30".', max_length=100)),
                ('default_net_days', models.PositiveIntegerField(default=30)),
                ('default_late_fee_policy', models.CharField(blank=True, help_text='Short line like "1.5% per month after 30 days".', max_length=255)),
                ('default_footer_text', models.TextField(blank=True, help_text='Footer / legal disclaimers displayed on invoices.')),
                ('pdf_header_layout', models.CharField(choices=[('stacked', 'Stacked (logo above address)'), ('inline-left', 'Inline (logo left, address right)'), ('inline-right', 'Inline (address left, logo right)')], default='inline-left', max_length=20)),
                ('header_logo_max_width_px', models.PositiveIntegerField(default=320, help_text='Render hint for PDF header logo max width.')),
                ('default_currency', models.CharField(default='USD', max_length=3)),
                ('default_locale', models.CharField(default='en_US', max_length=10)),
                ('timezone', models.CharField(default='America/Indiana/Indianapolis', max_length=64)),
                ('is_active', models.BooleanField(default=False, help_text='Only one active profile allowed per deployment.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', 'slug'],
            },
        ),
        migrations.DeleteModel(
            name='ClientProfile',
        ),
        migrations.AddConstraint(
            model_name='companyprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_company_profile'),
        ),
    ]
