# Generated by Django 4.2.20 on 2025-12-31 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0013_companyprofile_delete_clientprofile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('slug__isnull', False)), fields=('slug',), name='money_category_slug_unique_not_null'),
        ),
    ]
