# Generated by Django 4.2.20 on 2026-01-03 04:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('money', '0016_remove_client_user_alter_miles_vehicle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['business', 'last', 'first']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['service']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name']},
        ),
        migrations.RemoveConstraint(
            model_name='category',
            name='money_category_slug_unique_not_null',
        ),
        migrations.RemoveConstraint(
            model_name='invoicev2',
            name='uniq_invoicev2_number',
        ),
        migrations.RemoveIndex(
            model_name='invoicev2',
            name='money_invoi_invoice_f06be6_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoicev2',
            name='money_invoi_client__a190eb_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoicev2',
            name='money_invoi_event_i_e8d0c8_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoicev2',
            name='money_invoi_status_98844a_idx',
        ),
        migrations.RemoveIndex(
            model_name='miles',
            name='money_miles_mileage_8e62c1_idx',
        ),
        migrations.RemoveIndex(
            model_name='miles',
            name='money_miles_vehicle_fc6546_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='money_trans_date_fbbc99_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='money_trans_event_i_f9d321_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='money_trans_categor_3538f4_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='money_trans_sub_cat_c36845_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='money_trans_invoice_d1f344_idx',
        ),
        migrations.RemoveIndex(
            model_name='vehicleexpense',
            name='money_vehic_vehicle_4e338d_idx',
        ),
        migrations.RemoveIndex(
            model_name='vehicleexpense',
            name='money_vehic_expense_fb8ac2_idx',
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_year',
            field=models.PositiveIntegerField(db_index=True, default=2026, help_text='Year this event belongs to (used for reporting and invoice grouping).', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceitemv2',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoicev2',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='brand_color_primary',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color like #000000 or #fff.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='brand_color_secondary',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color like #000000 or #fff.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='default_footer_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='default_late_fee_policy',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='display_name',
            field=models.CharField(blank=True, help_text='Trade name; falls back to legal name if blank.', max_length=255),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='header_logo_max_width_px',
            field=models.PositiveIntegerField(default=320),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='logo_alt_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='pay_to_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='remittance_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='slug',
            field=models.SlugField(help_text="Short identifier (e.g., 'airborne-images', 'skyguy').", unique=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='tax_id_ein',
            field=models.CharField(blank=True, help_text='EIN / Tax ID displayed on invoices.', max_length=64),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legacy_invoices', to='money.client'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legacy_invoices', to='money.event'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legacy_invoices', to='money.service'),
        ),
        migrations.AlterField(
            model_name='invoicev2',
            name='event_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='invoicev2',
            name='from_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoicev2',
            name='from_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='invoicev2',
            name='from_footer_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoicev2',
            name='from_logo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoicev2',
            name='from_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='invoicev2',
            name='from_net_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='invoicev2',
            name='from_tax_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='invoicev2',
            name='from_terms',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='invoicev2',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoicev2',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='invoicev2',
            name='pdf_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='invoicev2',
            name='pdf_snapshot',
            field=models.FileField(blank=True, null=True, upload_to='invoices_v2/'),
        ),
        migrations.AlterField(
            model_name='invoicev2',
            name='pdf_snapshot_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoicev2',
            name='pdf_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='invoicev2',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoicev2',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_v2_emails_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoicev2',
            name='sent_to',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='invoicev2',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices_v2', to='money.service'),
        ),
        migrations.AlterField(
            model_name='invoicev2',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='mileagerate',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Optional: set per-user rates. Leave blank for a global rate.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mileage_rates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='miles',
            name='begin',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='miles',
            name='end',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='miles',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=1, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='miles',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='day',
            field=models.IntegerField(help_text='Day of the month to apply', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicleexpense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'category_type'], name='money_categ_user_id_f4ad93_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'category'], name='money_categ_user_id_327a1a_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'slug'], name='money_categ_user_id_b917b5_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['user', 'business'], name='money_clien_user_id_f6e8fb_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['user', 'email'], name='money_clien_user_id_37b66c_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['user', 'title'], name='money_event_user_id_1fd188_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['user', 'event_type'], name='money_event_user_id_ba26b3_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['user', 'event_year'], name='money_event_user_id_e44a35_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['user', 'slug'], name='money_event_user_id_dc88d2_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['date'], name='money_invoi_date_77223b_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='money_invoi_invoice_e9e5ca_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitemv2',
            index=models.Index(fields=['user', 'invoice'], name='money_invoi_user_id_796539_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitemv2',
            index=models.Index(fields=['user', 'sub_cat'], name='money_invoi_user_id_c4333d_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicev2',
            index=models.Index(fields=['user', 'invoice_number'], name='money_invoi_user_id_0e53e7_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicev2',
            index=models.Index(fields=['user', 'client', 'date'], name='money_invoi_user_id_c984c9_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicev2',
            index=models.Index(fields=['user', 'event', 'date'], name='money_invoi_user_id_4ae507_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicev2',
            index=models.Index(fields=['user', 'status'], name='money_invoi_user_id_4c76ea_idx'),
        ),
        migrations.AddIndex(
            model_name='miles',
            index=models.Index(fields=['user', 'vehicle'], name='money_miles_user_id_5bce39_idx'),
        ),
        migrations.AddIndex(
            model_name='miles',
            index=models.Index(fields=['user', 'mileage_type'], name='money_miles_user_id_e45cbb_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['user', 'date'], name='money_recei_user_id_a49218_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['user', 'invoice_number'], name='money_recei_user_id_5e89f6_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['user', 'service'], name='money_servi_user_id_df7ea0_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['user', 'sub_cat'], name='money_subca_user_id_e2e046_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['user', 'category'], name='money_subca_user_id_399e62_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['user', 'slug'], name='money_subca_user_id_2a2531_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['user', 'name'], name='money_team_user_id_9ab7e1_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'trans_type', 'date'], name='money_trans_user_id_f390c8_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'invoice_number'], name='money_trans_user_id_dfb184_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'event'], name='money_trans_user_id_a14bc7_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'category'], name='money_trans_user_id_f22760_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'sub_cat'], name='money_trans_user_id_6824bf_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['user', 'name'], name='money_vehic_user_id_9c8eb7_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleexpense',
            index=models.Index(fields=['user', 'vehicle', 'date'], name='money_vehic_user_id_22879f_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleexpense',
            index=models.Index(fields=['user', 'expense_type'], name='money_vehic_user_id_c5bceb_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleyear',
            index=models.Index(fields=['vehicle', 'tax_year'], name='money_vehic_vehicle_02df64_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('slug__isnull', False)), fields=('user', 'slug'), name='uniq_money_category_user_slug_not_null'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('user', 'email'), name='uniq_money_client_user_email'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(condition=models.Q(('slug__isnull', False)), fields=('user', 'slug'), name='uniq_money_event_user_slug_not_null'),
        ),
        migrations.AddConstraint(
            model_name='invoicev2',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice_number__isnull', False)), fields=('user', 'invoice_number'), name='uniq_invoicev2_user_number'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('user', 'service'), name='uniq_money_service_per_user'),
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('slug__isnull', False)), fields=('user', 'slug'), name='uniq_money_subcategory_user_slug_not_null'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='uniq_money_team_per_user'),
        ),
    ]
