# Generated by Django 4.2.20 on 2026-01-11 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0017_alter_client_options_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='include_in_pl_reports',
            field=models.BooleanField(default=True, help_text='If unchecked, this sub-category is excluded from Profit & Loss reports.'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], default='Expense', help_text='Default accounting nature for this category.', max_length=20),
        ),
    ]
