# Generated by Django 4.2.20 on 2026-01-16 04:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('money', '0018_subcategory_include_in_pl_reports_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_number', models.CharField(blank=True, help_text='Optional human-friendly ID, e.g. C-00023', max_length=20)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address1', models.CharField(blank=True, max_length=200)),
                ('address2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, help_text='2-letter state code', max_length=2, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$', 'Use 2-letter state code (e.g., IN).')])),
                ('zip_code', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{5}(-\\d{4})?$', 'Use ZIP format 12345 or 12345-6789.')])),
                ('entity_type', models.CharField(choices=[('individual_soleprop', 'Individual / Sole proprietor'), ('single_member_llc', 'Single-member LLC'), ('partnership_llc', 'Partnership / Multi-member LLC'), ('c_corp', 'C Corporation'), ('s_corp', 'S Corporation'), ('trust_estate', 'Trust / Estate'), ('other', 'Other')], max_length=30)),
                ('tin_type', models.CharField(blank=True, choices=[('ssn', 'SSN'), ('ein', 'EIN')], max_length=3)),
                ('tin_last4', models.CharField(blank=True, help_text='Last 4 digits only. Do not store full TIN.', max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Enter last 4 digits.')])),
                ('is_1099_eligible', models.BooleanField(default=True, help_text='Whether this contractor should receive a 1099 (default True; you can override).')),
                ('w9_status', models.CharField(choices=[('not_requested', 'Not requested'), ('requested', 'Requested'), ('received', 'Received'), ('verified', 'Verified')], default='not_requested', max_length=20)),
                ('w9_sent_date', models.DateField(blank=True, null=True)),
                ('w9_received_date', models.DateField(blank=True, null=True)),
                ('w9_document', models.FileField(blank=True, help_text='Store W-9 PDF (S3). Do not store full TIN in DB.', upload_to='money/tax-documents/w9/%Y/')),
                ('notes', models.TextField(blank=True)),
                ('edelivery_consent', models.BooleanField(default=False)),
                ('edelivery_consent_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.AlterField(
            model_name='category',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoiceitemv2',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoicev2',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='miles',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='service',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicleexpense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
        migrations.AddIndex(
            model_name='contractor',
            index=models.Index(fields=['user', 'is_active'], name='money_contr_user_id_3e8259_idx'),
        ),
        migrations.AddIndex(
            model_name='contractor',
            index=models.Index(fields=['user', 'last_name', 'first_name'], name='money_contr_user_id_43c53c_idx'),
        ),
        migrations.AddConstraint(
            model_name='contractor',
            constraint=models.UniqueConstraint(condition=models.Q(('contractor_number', ''), _negated=True), fields=('user', 'contractor_number'), name='uniq_contractor_number_per_user'),
        ),
    ]
