# Generated by Django 4.2.20 on 2026-01-18 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0020_transaction_contractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Optional. Attach a client to this job for reporting and defaults.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='money.client'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('commercial', 'Commercial'), ('event', 'Event'), ('inspection', 'Inspection'), ('mapping', 'Mapping'), ('Construction', 'Construction'), ('marketing', 'Marketing'), ('real-estate', 'Real Estate'), ('internal', 'Internal'), ('training', 'training'), ('race', 'Race'), ('other', 'Other')], default='race', max_length=50),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['user', 'client'], name='money_event_user_id_c734a8_idx'),
        ),
    ]
