# Generated by Django 4.2.20 on 2026-01-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0021_event_client_alter_event_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('race', 'Race'), ('live_event', 'Live Event'), ('real_estate', 'Real Estate'), ('inspection', 'Inspection'), ('construction', 'Construction'), ('photography', 'Photography'), ('mapping', 'Mapping'), ('marketing', 'Marketing'), ('commercial', 'Commercial'), ('training', 'Training'), ('internal', 'Internal'), ('other', 'Other')], default='race', max_length=50),
        ),
    ]
