# Generated by Django 4.2.20 on 2026-01-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0022_alter_event_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobNumberCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('segment', models.CharField(db_index=True, max_length=30)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='job_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('commercial', 'Commercial'), ('real_estate', 'Real Estate'), ('inspection', 'Inspection'), ('construction', 'Construction'), ('photography', 'Photography'), ('mapping', 'Mapping'), ('training', 'Training'), ('internal', 'Internal'), ('other', 'Other')], default='race', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='jobnumbercounter',
            constraint=models.UniqueConstraint(fields=('year', 'segment'), name='uniq_job_counter_year_segment'),
        ),
    ]
