# Generated by Django 4.2.20 on 2026-01-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0023_jobnumbercounter_event_job_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['event_year', 'job_number', 'title']},
        ),
        migrations.RemoveConstraint(
            model_name='jobnumbercounter',
            name='uniq_job_counter_year_segment',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='money_event_user_id_1fd188_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='money_event_user_id_ba26b3_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='money_event_user_id_c734a8_idx',
        ),
        migrations.RemoveField(
            model_name='jobnumbercounter',
            name='last_number',
        ),
        migrations.RemoveField(
            model_name='jobnumbercounter',
            name='segment',
        ),
        migrations.AddField(
            model_name='jobnumbercounter',
            name='last_seq',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobnumbercounter',
            name='segment_digit',
            field=models.PositiveSmallIntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['user', 'event_year', 'job_number'], name='money_event_user_id_3130c6_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['job_number'], name='money_event_job_num_14b3fe_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_year'], name='money_event_event_y_e79b6f_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type'], name='money_event_event_t_3cdb8d_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['client'], name='money_event_client__a5cbed_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(condition=models.Q(('job_number__isnull', False)), fields=('event_year', 'job_number'), name='uniq_money_event_year_job_number_not_null'),
        ),
        migrations.AddConstraint(
            model_name='jobnumbercounter',
            constraint=models.UniqueConstraint(fields=('year', 'segment_digit'), name='uniq_money_job_counter_year_segment'),
        ),
    ]
