# Generated by Django 4.2.20 on 2026-01-22 01:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0024_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('commercial', 'Commercial'), ('real_estate', 'Real Estate'), ('inspection', 'Inspection'), ('construction', 'Construction'), ('photography', 'Photography'), ('mapping', 'Mapping'), ('training', 'Training'), ('internal', 'Internal'), ('other', 'Other')], default='commercial', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_year',
            field=models.PositiveIntegerField(db_index=True, default=2026, help_text='Year this job belongs to (used for reporting and invoice grouping).', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
