# Generated by Django 4.2.20 on 2026-01-24 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('money', '0025_alter_event_event_type_alter_event_event_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorW9Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', encrypted_fields.fields.EncryptedCharField(max_length=200)),
                ('business_name', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=200)),
                ('tax_classification', encrypted_fields.fields.EncryptedCharField(max_length=30)),
                ('llc_tax_class', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=5)),
                ('other_tax_class', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=100)),
                ('address_line1', encrypted_fields.fields.EncryptedCharField(max_length=200)),
                ('address_line2', encrypted_fields.fields.EncryptedCharField(max_length=200)),
                ('tin_type', encrypted_fields.fields.EncryptedCharField(max_length=10)),
                ('tin', encrypted_fields.fields.EncryptedCharField(max_length=32)),
                ('signature_name', encrypted_fields.fields.EncryptedCharField(max_length=200)),
                ('signature_data', encrypted_fields.fields.EncryptedTextField(blank=True)),
                ('attested', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('submitted_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('submitted_ua', models.TextField(blank=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='w9_submissions', to='money.contractor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at', '-id'],
            },
        ),
    ]
