# Generated by Django 4.2.20 on 2026-01-24 02:25

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0026_contractorw9submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorw9submission',
            name='business_name',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='contractorw9submission',
            name='llc_tax_class',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='contractorw9submission',
            name='other_tax_class',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=100),
        ),
    ]
