# Generated by Django 4.2.20 on 2026-01-24 02:32

from django.db import migrations, models
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0027_alter_contractorw9submission_business_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorw9submission',
            name='address_line1',
            field=encrypted_fields.fields.EncryptedCharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='contractorw9submission',
            name='address_line2',
            field=encrypted_fields.fields.EncryptedCharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='contractorw9submission',
            name='full_name',
            field=encrypted_fields.fields.EncryptedCharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='contractorw9submission',
            name='signature_data',
            field=encrypted_fields.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='contractorw9submission',
            name='signature_name',
            field=encrypted_fields.fields.EncryptedCharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='contractorw9submission',
            name='submitted_ua',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='contractorw9submission',
            name='tax_classification',
            field=encrypted_fields.fields.EncryptedCharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='contractorw9submission',
            name='tin',
            field=encrypted_fields.fields.EncryptedCharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='contractorw9submission',
            name='tin_type',
            field=encrypted_fields.fields.EncryptedCharField(default='', max_length=10),
        ),
    ]
