# Generated by Django 4.2.20 on 2026-01-24 03:22

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0028_alter_contractorw9submission_address_line1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorw9submission',
            name='business_name',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contractorw9submission',
            name='llc_tax_class',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='contractorw9submission',
            name='other_tax_class',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contractorw9submission',
            name='signature_data',
            field=encrypted_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
