# Generated by Django 4.2.20 on 2026-01-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0030_companyprofile_state_dropdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='state_1099_reporting_enabled',
            field=models.BooleanField(default=False, help_text='Enable state 1099 reporting boxes (Boxes 5–7) on 1099 PDFs.'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='state',
            field=models.CharField(blank=True, choices=[('AL', 'AL — Alabama'), ('AK', 'AK — Alaska'), ('AZ', 'AZ — Arizona'), ('AR', 'AR — Arkansas'), ('CA', 'CA — California'), ('CO', 'CO — Colorado'), ('CT', 'CT — Connecticut'), ('DE', 'DE — Delaware'), ('DC', 'DC — District of Columbia'), ('FL', 'FL — Florida'), ('GA', 'GA — Georgia'), ('HI', 'HI — Hawaii'), ('ID', 'ID — Idaho'), ('IL', 'IL — Illinois'), ('IN', 'IN — Indiana'), ('IA', 'IA — Iowa'), ('KS', 'KS — Kansas'), ('KY', 'KY — Kentucky'), ('LA', 'LA — Louisiana'), ('ME', 'ME — Maine'), ('MD', 'MD — Maryland'), ('MA', 'MA — Massachusetts'), ('MI', 'MI — Michigan'), ('MN', 'MN — Minnesota'), ('MS', 'MS — Mississippi'), ('MO', 'MO — Missouri'), ('MT', 'MT — Montana'), ('NE', 'NE — Nebraska'), ('NV', 'NV — Nevada'), ('NH', 'NH — New Hampshire'), ('NJ', 'NJ — New Jersey'), ('NM', 'NM — New Mexico'), ('NY', 'NY — New York'), ('NC', 'NC — North Carolina'), ('ND', 'ND — North Dakota'), ('OH', 'OH — Ohio'), ('OK', 'OK — Oklahoma'), ('OR', 'OR — Oregon'), ('PA', 'PA — Pennsylvania'), ('RI', 'RI — Rhode Island'), ('SC', 'SC — South Carolina'), ('SD', 'SD — South Dakota'), ('TN', 'TN — Tennessee'), ('TX', 'TX — Texas'), ('UT', 'UT — Utah'), ('VT', 'VT — Vermont'), ('VA', 'VA — Virginia'), ('WA', 'WA — Washington'), ('WV', 'WV — West Virginia'), ('WI', 'WI — Wisconsin'), ('WY', 'WY — Wyoming')], max_length=2),
        ),
    ]
