# Generated by Django 4.2.20 on 2026-01-26 05:00

from django.db import migrations, models
import money.models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0033_alter_contractor_city_alter_contractor_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='w9_document',
            field=models.FileField(blank=True, help_text='Store W-9 PDF (S3). Do not store full TIN in DB.', null=True, upload_to=money.models.contractor_w9_upload_path),
        ),
    ]
