# Generated by Django 4.2.20 on 2026-01-26 17:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import money.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('money', '0034_alter_contractor_w9_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor1099',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_year', models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('copy_b_pdf', models.FileField(blank=True, null=True, upload_to=money.models.contractor_1099_upload_path)),
                ('copy_1_pdf', models.FileField(blank=True, null=True, upload_to=money.models.contractor_1099_upload_path)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('emailed_to', models.EmailField(blank=True, max_length=254)),
                ('email_count', models.PositiveIntegerField(default=0)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms_1099', to='money.contractor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tax_year', '-generated_at', '-id'],
                'indexes': [models.Index(fields=['user', 'tax_year'], name='money_contr_user_id_744c78_idx'), models.Index(fields=['user', 'contractor', 'tax_year'], name='money_contr_user_id_c89510_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='contractor1099',
            constraint=models.UniqueConstraint(fields=('user', 'contractor', 'tax_year'), name='uniq_1099_per_user_contractor_year'),
        ),
    ]
