# Generated by Django 4.2.20 on 2025-11-20 02:43

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('equipment_type', models.CharField(choices=[('Drone', 'Drone'), ('Controller', 'Controller'), ('Battery', 'Battery'), ('Charger', 'Charger'), ('Accessory', 'Accessory'), ('Other', 'Other')], max_length=50)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=200)),
                ('serial_number', models.CharField(blank=True, max_length=200)),
                ('faa_number', models.CharField(blank=True, max_length=100)),
                ('faa_certificate', models.FileField(blank=True, null=True, upload_to='registrations/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])])),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the original purchase cost of the equipment.', max_digits=10, null=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])])),
                ('date_sold', models.DateField(blank=True, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deducted_full_cost', models.BooleanField(default=True)),
                ('active', models.BooleanField(default='True')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Equipment',
                'ordering': ['equipment_type', 'name'],
            },
        ),
    ]
