# Generated by Django 4.2.20 on 2025-12-02 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='equipment',
            table='flightplan_equipment',
        ),
    ]
