# Generated by Django 4.2.20 on 2025-12-06 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_equipment_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroneSafetyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('DJI', 'DJI'), ('Autel', 'Autel'), ('Skydio', 'Skydio'), ('Other', 'Other')], help_text='Manufacturer name, e.g. DJI, Autel.', max_length=50)),
                ('model_name', models.CharField(help_text="Short model name, e.g. 'Mavic 4 Pro', 'EVO II Pro'.", max_length=100)),
                ('full_display_name', models.CharField(help_text="Friendly full name, e.g. 'DJI Mavic 4 Pro'.", max_length=150, unique=True)),
                ('year_released', models.PositiveIntegerField(blank=True, help_text='Approximate year the drone was released (optional).', null=True)),
                ('is_enterprise', models.BooleanField(default=False, help_text='Check if this is an Enterprise / commercial series aircraft.')),
                ('safety_features', models.TextField(help_text='Plain text or bullet list of safety features. This will be used to pre-fill waiver safety sections.')),
                ('aka_names', models.CharField(blank=True, help_text="Optional comma-separated alternate names, e.g. 'M4P, Mavic 4 Pro, Mavic 4'. Used when matching user input.", max_length=255)),
                ('active', models.BooleanField(default=True, help_text='Uncheck to hide this profile from suggestions without deleting it.')),
            ],
            options={
                'verbose_name': 'Drone safety profile',
                'verbose_name_plural': 'Drone safety profiles',
                'ordering': ['brand', 'model_name'],
                'unique_together': {('brand', 'model_name')},
            },
        ),
    ]
