# Generated by Django 4.2.20 on 2025-12-06 01:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_dronesafetyprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dronesafetyprofile',
            options={'ordering': ['brand', 'model_name'], 'verbose_name': 'Drone Safety Profile', 'verbose_name_plural': 'Drone Safety Profiles'},
        ),
        migrations.RemoveField(
            model_name='dronesafetyprofile',
            name='is_enterprise',
        ),
        migrations.RemoveField(
            model_name='dronesafetyprofile',
            name='year_released',
        ),
        migrations.AddField(
            model_name='dronesafetyprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dronesafetyprofile',
            name='discontinued_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Year discontinued (if applicable).', null=True),
        ),
        migrations.AddField(
            model_name='dronesafetyprofile',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional extra notes (firmware, variants, certs, etc.).'),
        ),
        migrations.AddField(
            model_name='dronesafetyprofile',
            name='released_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Approximate release year (optional).', null=True),
        ),
        migrations.AddField(
            model_name='dronesafetyprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='drone_safety_profile',
            field=models.ForeignKey(blank=True, help_text='If set, this links this piece of equipment to a known safety profile.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_items', to='equipment.dronesafetyprofile'),
        ),
        migrations.AlterField(
            model_name='dronesafetyprofile',
            name='active',
            field=models.BooleanField(default=True, help_text='Uncheck if this profile should no longer be suggested.'),
        ),
        migrations.AlterField(
            model_name='dronesafetyprofile',
            name='aka_names',
            field=models.TextField(blank=True, help_text="Optional alternate names, nicknames, or variations. One per line, e.g. 'M4P', 'Mavic 4 Pro Cine'."),
        ),
        migrations.AlterField(
            model_name='dronesafetyprofile',
            name='brand',
            field=models.CharField(choices=[('DJI', 'DJI'), ('DJI Enterprise', 'DJI Enterprise'), ('Autel', 'Autel'), ('Skydio', 'Skydio'), ('Other', 'Other')], default='DJI', help_text='Manufacturer / brand of the aircraft.', max_length=50),
        ),
        migrations.AlterField(
            model_name='dronesafetyprofile',
            name='full_display_name',
            field=models.CharField(help_text="Canonical display name, e.g. 'DJI Mavic 4 Pro'.", max_length=150),
        ),
        migrations.AlterField(
            model_name='dronesafetyprofile',
            name='model_name',
            field=models.CharField(help_text="Short model name, e.g. 'Mavic 4 Pro', 'Evo II Pro'.", max_length=100),
        ),
        migrations.AlterField(
            model_name='dronesafetyprofile',
            name='safety_features',
            field=models.TextField(help_text='Bulleted or paragraph list of key safety features. Example: return-to-home, obstacle avoidance, ADS-B In, care refresh, geo-fencing, parachute system, etc.'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(choices=[('Drone', 'Drone'), ('Battery', 'Battery'), ('Controller', 'Controller'), ('Other', 'Other')], default='Drone', max_length=50),
        ),
    ]
