# Generated by Django 4.2.20 on 2025-12-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_alter_dronesafetyprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dronesafetyprofile',
            name='year_released',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Approximate release year (optional).', null=True),
        ),
    ]
