# Generated by Django 4.2.20 on 2025-12-30 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_alter_dronesafetyprofile_year_released'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dronesafetyprofile',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='dronesafetyprofile',
            constraint=models.UniqueConstraint(fields=('brand', 'model_name'), name='uniq_dronesafetyprofile_brand_model'),
        ),
    ]
