# Generated by Django 4.2.20 on 2025-12-31 20:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_alter_dronesafetyprofile_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='business_use_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional: business-use percentage (0-100). Useful for mixed-use assets like a travel trailer.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='equipment',
            name='depreciation_method',
            field=models.CharField(choices=[('MACRS', 'MACRS'), ('SL', 'Straight-line')], default='MACRS', help_text='Optional: depreciation approach used for planning/reporting.', max_length=10),
        ),
        migrations.AddField(
            model_name='equipment',
            name='placed_in_service_date',
            field=models.DateField(blank=True, help_text='Date the asset was first placed in service for business use (may differ from purchase date).', null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='property_type',
            field=models.CharField(choices=[('1245', 'Section 1245 (Depreciable personal property)'), ('1250', 'Section 1250 (Depreciable real property)')], default='1245', help_text='Tax classification for gain/loss reporting (e.g., Form 4797).', max_length=10),
        ),
        migrations.AddField(
            model_name='equipment',
            name='useful_life_years',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Optional: useful life in years (for planning/straight-line cases).', null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='deducted_full_cost',
            field=models.BooleanField(default=True, help_text='If True, indicates the cost was fully expensed (e.g., Section 179/bonus) rather than depreciated over time.'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='drone_safety_profile',
            field=models.ForeignKey(blank=True, help_text='If set, links this equipment item to a known safety profile (drones only).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_items', to='equipment.dronesafetyprofile'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(choices=[('Drone', 'Drone'), ('Battery', 'Battery'), ('Controller', 'Controller'), ('Camera', 'Camera'), ('Lens', 'Lens'), ('Vehicle', 'Vehicle'), ('Trailer', 'Trailer'), ('Other', 'Other')], default='Drone', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='purchase_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original purchase cost (basis) of this item.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gross sale proceeds received for this item.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
