# Generated by Django 4.2.20 on 2026-01-02 17:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import equipment.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0007_equipment_business_use_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dronesafetyprofile',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dronesafetyprofile',
            name='aka_names',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='dronesafetyprofile',
            name='brand',
            field=models.CharField(choices=[('DJI', 'DJI'), ('DJI Enterprise', 'DJI Enterprise'), ('Autel', 'Autel'), ('Skydio', 'Skydio'), ('Other', 'Other')], default='DJI', max_length=50),
        ),
        migrations.AlterField(
            model_name='dronesafetyprofile',
            name='full_display_name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='dronesafetyprofile',
            name='is_enterprise',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dronesafetyprofile',
            name='model_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dronesafetyprofile',
            name='safety_features',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dronesafetyprofile',
            name='year_released',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='faa_certificate',
            field=models.FileField(blank=True, null=True, upload_to=equipment.models.registration_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to=equipment.models.receipt_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
    ]
