# Generated by Django 4.2.20 on 2025-12-05 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirspaceWaiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('timeframe', models.CharField(choices=[('sunrise_noon', 'Sunrise to Noon'), ('noon_4pm', 'Noon to 4 PM'), ('4pm_sunset', '4 PM to Sunset'), ('night', 'Night')], max_length=20)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('local_timezone', models.CharField(max_length=64)),
                ('proposed_location', models.TextField()),
                ('max_agl', models.PositiveIntegerField(help_text='Maximum altitude AGL in feet')),
                ('lat_degrees', models.PositiveSmallIntegerField()),
                ('lat_minutes', models.PositiveSmallIntegerField()),
                ('lat_seconds', models.DecimalField(decimal_places=4, max_digits=7)),
                ('lat_direction', models.CharField(choices=[('N', 'N'), ('S', 'S')], max_length=1)),
                ('lon_degrees', models.PositiveSmallIntegerField()),
                ('lon_minutes', models.PositiveSmallIntegerField()),
                ('lon_seconds', models.DecimalField(decimal_places=4, max_digits=7)),
                ('lon_direction', models.CharField(choices=[('E', 'E'), ('W', 'W')], max_length=1)),
                ('radius_nm', models.DecimalField(decimal_places=2, max_digits=4)),
                ('nearest_airport', models.CharField(max_length=10)),
                ('airspace_class', models.CharField(choices=[('B', 'Class B'), ('C', 'Class C'), ('D', 'Class D'), ('E', 'Class E'), ('G', 'Class G')], max_length=1)),
                ('lat_decimal', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lon_decimal', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('short_description', models.TextField()),
                ('has_related_waiver', models.BooleanField(default=False)),
                ('related_waiver_details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airspace_waivers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Airspace Waiver',
                'verbose_name_plural': 'Airspace Waivers',
                'ordering': ['-created_at'],
            },
        ),
    ]
