# Generated by Django 4.2.20 on 2025-12-10 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_generaldocument_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pilot', '0002_alter_pilotprofile_table_alter_training_table'),
        ('equipment', '0005_alter_dronesafetyprofile_year_released'),
        ('airspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaiverPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_title', models.CharField(help_text="Short title for this operation (e.g., 'NHRA Nationals FPV Coverage').", max_length=255)),
                ('start_date', models.DateField(help_text='First date on which operations will occur.')),
                ('end_date', models.DateField(blank=True, help_text='Last date on which operations will occur (optional if single day).', null=True)),
                ('timeframe', models.CharField(choices=[('sunrise_noon', 'Sunrise to Noon'), ('noon_4pm', 'Noon to 4 PM'), ('4pm_sunset', '4 PM to Sunset'), ('night', 'Night')], help_text='General time of day when operations will occur.', max_length=20)),
                ('frequency', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly')], help_text='How often operations will occur during this date range.', max_length=20)),
                ('local_time_zone', models.CharField(blank=True, help_text='Local time zone for the operation (e.g., America/New_York).', max_length=64)),
                ('proposed_agl', models.PositiveIntegerField(blank=True, help_text='Maximum planned altitude AGL in feet.', null=True)),
                ('aircraft_manual', models.CharField(blank=True, help_text='If needed, manually describe any additional aircraft types.', max_length=255)),
                ('pilot_name_manual', models.CharField(blank=True, help_text='Manual pilot name override, if not using a profile.', max_length=255)),
                ('pilot_cert_manual', models.CharField(blank=True, help_text='Manual Part 107 certificate number, if not using a profile.', max_length=255)),
                ('pilot_flight_hours', models.DecimalField(blank=True, decimal_places=1, help_text='Approximate total UAS flight hours for this pilot.', max_digits=7, null=True)),
                ('operates_under_10739', models.BooleanField(default=False, help_text='Check if this operation will be conducted under an approved 14 CFR §107.39 Operations Over People waiver.')),
                ('oop_waiver_number', models.CharField(blank=True, help_text='Example: 107W-2024-01234', max_length=100, verbose_name='Approved 107.39 Waiver Number')),
                ('venue_name', models.CharField(blank=True, help_text="Name of the venue (e.g., 'Lucas Oil Raceway').", max_length=255)),
                ('venue_address', models.CharField(blank=True, help_text='Street address of the venue.', max_length=255)),
                ('location_city', models.CharField(blank=True, help_text='City where the operation will occur.', max_length=100)),
                ('location_state', models.CharField(blank=True, help_text='State where the operation will occur.', max_length=100)),
                ('location_latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude of the center point for operations.', max_digits=9, null=True)),
                ('location_longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude of the center point for operations.', max_digits=9, null=True)),
                ('location_radius', models.PositiveIntegerField(blank=True, help_text='Radius from the center point (in feet) where operations will occur.', null=True)),
                ('nearest_airport', models.CharField(blank=True, help_text="Nearest airport (e.g., 'KIND – Indianapolis Intl').", max_length=255)),
                ('launch_location', models.CharField(blank=True, help_text='Typical launch location or staging area for this waiver.', max_length=255)),
                ('uses_drone_detection', models.BooleanField(default=False, help_text='Drone detection system (e.g., AirSentinel) will be used.')),
                ('uses_flight_tracking', models.BooleanField(default=False, help_text='Flight tracking (e.g., FlightAware / ADS-B) will be monitored.')),
                ('has_visual_observer', models.BooleanField(default=False, help_text='One or more Visual Observers will be used.')),
                ('visual_observer_names', models.CharField(blank=True, help_text='Names of Visual Observers, if applicable.', max_length=255)),
                ('insurance_provider', models.CharField(blank=True, help_text='Insurance provider for this operation (optional).', max_length=255)),
                ('insurance_coverage_limit', models.CharField(blank=True, help_text="Coverage limit (e.g., '$5,000,000').", max_length=100)),
                ('safety_features_notes', models.TextField(blank=True, help_text='Key safety features, redundancies, or geofencing used for this operation. If a drone with a safety profile is selected, this will be auto-filled.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(blank=True, help_text='Select a drone from your equipment list (optional).', limit_choices_to={'equipment_type': 'Drone'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiver_planning_entries', to='equipment.equipment')),
                ('oop_waiver_document', models.ForeignKey(blank=True, help_text='Select your approved 107.39 waiver from General Documents.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oop_waiver_planning_entries', to='documents.generaldocument')),
                ('pilot_profile', models.ForeignKey(blank=True, help_text='Pilot selected from your Pilot Profile app (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiver_planning_entries', to='pilot.pilotprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiver_planning_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Waiver Planning Entry',
                'verbose_name_plural': 'Waiver Planning Entries',
                'ordering': ['-created_at'],
            },
        ),

    ]
