# Generated by Django 4.2.20 on 2025-12-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airspacewaiver',
            name='conops_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airspacewaiver',
            name='conops_text',
            field=models.TextField(blank=True),
        ),
    ]
