# Generated by Django 4.2.20 on 2025-12-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airspace', '0002_waiverplanning_delete_airspacewaiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name="waiverplanning",
            name="venue_address",
        ),
        migrations.AddField(
            model_name="waiverplanning",
            name="street_address",
            field=models.CharField(...),
        ),
        migrations.AddField(
            model_name="waiverplanning",
            name="zip_code",
            field=models.CharField(...),
        ),
        migrations.AlterField(
            model_name="waiverplanning",
            name="location_radius",
            field=models.CharField(...),
        ),
    ]

