# Generated by Django 4.2.20 on 2025-12-05 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_equipment_table'),
        ('airspace', '0002_airspacewaiver_conops_generated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airspacewaiver',
            name='aircraft',
            field=models.ForeignKey(blank=True, help_text='Select a drone from your equipment list (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airspace_waivers', to='equipment.equipment'),
        ),
        migrations.AddField(
            model_name='airspacewaiver',
            name='aircraft_custom',
            field=models.CharField(blank=True, help_text='If not in the list, describe the aircraft here.', max_length=255),
        ),
    ]
