# Generated by Django 4.2.20 on 2025-12-11 20:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airspace", "0003_remove_waiverplanning_venue_address_and_more"),
    ]

    operations = [
        # --------------------------------------------------------
        # STATE-ONLY: purpose_operations + purpose_operations_details
        # The columns already exist in the DB, so we only need to
        # update Django's migration STATE, not the actual database.
        # --------------------------------------------------------
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="waiverplanning",
                    name="purpose_operations",
                    field=django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("event_filming", "Event filming / broadcast"),
                                ("pro_photography", "Professional aerial photography"),
                                ("mapping_survey", "Mapping / survey"),
                                ("infrastructure_inspection", "Infrastructure inspection"),
                                ("public_safety", "Public safety / incident support"),
                                ("training_proficiency", "Training / proficiency flights"),
                                ("real_estate", "Real estate photography"),
                            ],
                            max_length=50,
                        ),
                        blank=True,
                        default=list,
                        help_text="Select all purposes that apply to this operation.",
                        size=None,
                    ),
                ),
                migrations.AddField(
                    model_name="waiverplanning",
                    name="purpose_operations_details",
                    field=models.TextField(
                        blank=True,
                        null=True,
                        help_text="Additional context about how the drone will be used.",
                    ),
                ),
            ],
        ),

        # --------------------------------------------------------
        # These AlterField operations are safe to run on the DB.
        # --------------------------------------------------------
        migrations.AlterField(
            model_name="waiverplanning",
            name="location_radius",
            field=models.CharField(
                blank=True,
                null=True,
                max_length=20,
                help_text="Radius from the center point (in NM or blanket area).",
            ),
        ),
        migrations.AlterField(
            model_name="waiverplanning",
            name="street_address",
            field=models.CharField(
                blank=True,
                max_length=255,
                help_text="Street address of the venue or operation area.",
            ),
        ),
        migrations.AlterField(
            model_name="waiverplanning",
            name="timeframe",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("sunrise_noon", "Sunrise to Noon"),
                        ("noon_4pm", "Noon to 4 PM"),
                        ("4pm_sunset", "4 PM to Sunset"),
                        ("night", "Night"),
                    ],
                    max_length=20,
                ),
                blank=True,
                default=list,
                help_text="Select all timeframes you expect to operate.",
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="waiverplanning",
            name="zip_code",
            field=models.CharField(
                blank=True,
                max_length=20,
                help_text="ZIP or postal code for the operation location.",
            ),
        ),

        # NOTE: We intentionally do NOT delete AirspaceWaiver here.
        # The model is gone from code and the DB table is already dropped,
        # so attempting a DeleteModel would fail.
    ]
