# Generated by Django 4.2.20 on 2025-12-05 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_equipment_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pilot', '0002_alter_pilotprofile_table_alter_training_table'),
        ('airspace', '0003_airspacewaiver_aircraft_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaiverPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_manual', models.CharField(blank=True, help_text='If needed, manually describe any additional aircraft types.', max_length=255)),
                ('pilot_name_manual', models.CharField(blank=True, help_text='Manual pilot name override, if not using a profile.', max_length=255)),
                ('pilot_cert_manual', models.CharField(blank=True, help_text='Manual Part 107 certificate number, if not using a profile.', max_length=255)),
                ('pilot_flight_hours', models.DecimalField(blank=True, decimal_places=1, help_text='Approximate total UAS flight hours for this pilot.', max_digits=7, null=True)),
                ('launch_location', models.CharField(blank=True, help_text='Typical launch location or staging area for this waiver.', max_length=255)),
                ('safety_features_notes', models.TextField(blank=True, help_text='Key safety features, redundancies, or geofencing used for this operation.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(blank=True, help_text='Select a drone from your equipment list (optional).', limit_choices_to={'equipment_type': 'Drone'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiver_planning_entries', to='equipment.equipment')),
                ('pilot_profile', models.ForeignKey(blank=True, help_text='Pilot selected from your Pilot Profile app (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiver_planning_entries', to='pilot.pilotprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiver_planning_entries', to=settings.AUTH_USER_MODEL)),
                ('waiver', models.OneToOneField(blank=True, help_text='Linked waiver. May be null until the FAA waiver form is submitted.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planning', to='airspace.airspacewaiver')),
            ],
            options={
                'verbose_name': 'Waiver Planning Entry',
                'verbose_name_plural': 'Waiver Planning Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
