# Generated by Django 4.2.20 on 2025-12-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airspace', '0004_waiverplanning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiverplanning',
            name='safety_features_notes',
            field=models.TextField(blank=True, help_text='Key safety features, redundancies, or geofencing used for this operation. If a drone with a safety profile is selected, this will be auto-filled.'),
        ),
    ]
