# Generated by Django 4.2.20 on 2025-12-11 20:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airspace", "0004_waiverplanning_purpose_operations_and_more"),
    ]

    operations = [
        # --------------------------------------------------------
        # New Operational Profile & Environment fields
        # --------------------------------------------------------
        migrations.AddField(
            model_name="waiverplanning",
            name="aircraft_count",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Single aircraft"),
                    ("multi_sequential", "Multiple aircraft (sequential use)"),
                    ("multi_simultaneous", "Multiple aircraft (simultaneous use)"),
                ],
                help_text="Number of aircraft used for this operation.",
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="waiverplanning",
            name="estimated_crowd_size",
            field=models.CharField(
                blank=True,
                help_text="Estimated maximum crowd size (e.g., 15,000).",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="waiverplanning",
            name="flight_duration",
            field=models.CharField(
                blank=True,
                help_text="Typical flight duration (e.g., 5–10 min).",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="waiverplanning",
            name="flights_per_day",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                help_text="Approximate number of flights per day.",
            ),
        ),
        migrations.AddField(
            model_name="waiverplanning",
            name="ground_environment",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("spectator_stands", "Spectator stands"),
                        ("pits_staff", "Pit / staff-only areas"),
                        ("general_admission", "General admission / open grounds"),
                        ("restricted_zones", "Restricted or barricaded zones"),
                    ],
                    max_length=50,
                ),
                blank=True,
                default=list,
                help_text="Types of ground environment present in the area.",
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="waiverplanning",
            name="lighting_conditions",
            field=models.CharField(
                blank=True,
                choices=[
                    ("day", "Day only"),
                    ("day_twilight", "Day + Civil Twilight"),
                    ("night", "Night operations included"),
                ],
                help_text="Lighting conditions under which flights will occur.",
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="waiverplanning",
            name="over_moving_vehicles",
            field=models.BooleanField(
                default=False,
                help_text="Operations conducted over moving vehicles.",
            ),
        ),
        migrations.AddField(
            model_name="waiverplanning",
            name="prepared_procedures",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("preflight", "Pre-flight checklist used"),
                        ("postflight", "Post-flight checklist used"),
                        ("lost_link", "Lost-link / flyaway procedure in place"),
                        ("emergency_lz", "Emergency landing zones pre-identified"),
                    ],
                    max_length=30,
                ),
                blank=True,
                default=list,
                help_text="Safety procedures used during operations.",
                size=None,
            ),
        ),

        # --------------------------------------------------------
        # STATE-ONLY removal of AirspaceWaiver
        # (table already gone; do not try to drop it again)
        # --------------------------------------------------------
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name="AirspaceWaiver",
                ),
            ],
        ),
    ]
