# Generated by Django 4.2.20 on 2025-12-07 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_generaldocument_category'),
        ('airspace', '0005_alter_waiverplanning_safety_features_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiverplanning',
            name='oop_waiver_document',
            field=models.ForeignKey(blank=True, help_text='Select your approved 107.39 waiver from General Documents.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oop_waiver_planning_entries', to='documents.generaldocument'),
        ),
        migrations.AddField(
            model_name='waiverplanning',
            name='oop_waiver_number',
            field=models.CharField(blank=True, help_text='Example: 107W-2024-01234', max_length=100, verbose_name='Approved 107.39 Waiver Number'),
        ),
        migrations.AddField(
            model_name='waiverplanning',
            name='operates_under_10739',
            field=models.BooleanField(default=False, help_text='Check if this operation will be conducted under an approved 14 CFR §107.39 Operations Over People waiver.'),
        ),
    ]
