# Generated by Django 4.2.20 on 2025-12-11 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_generaldocument_category'),
        ('airspace', '0005_waiverplanning_aircraft_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waiverplanning',
            name='lighting_conditions',
        ),
        migrations.RemoveField(
            model_name='waiverplanning',
            name='over_moving_vehicles',
        ),
        migrations.RemoveField(
            model_name='waiverplanning',
            name='visual_observer_names',
        ),
        migrations.AddField(
            model_name='waiverplanning',
            name='mv_waiver_document',
            field=models.ForeignKey(blank=True, help_text='Select your approved 107.145 waiver from General Documents.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mv_waiver_planning_entries', to='documents.generaldocument'),
        ),
        migrations.AddField(
            model_name='waiverplanning',
            name='mv_waiver_number',
            field=models.CharField(blank=True, help_text='Example: 107W-2024-04567', max_length=100, verbose_name='Approved 107.145 Waiver Number'),
        ),
        migrations.AddField(
            model_name='waiverplanning',
            name='operates_under_107145',
            field=models.BooleanField(default=False, help_text='Check if this operation will be conducted under an approved 14 CFR §107.145 Operations Over Moving Vehicles waiver.'),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='estimated_crowd_size',
            field=models.CharField(blank=True, help_text='Estimated maximum crowd size (e.g., 15,000). Leave blank if unknown.', max_length=50),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='flights_per_day',
            field=models.PositiveIntegerField(blank=True, help_text='Approximate number of flights per day (used for narrative only).', null=True),
        ),
    ]
