# Generated by Django 4.2.20 on 2025-12-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airspace', '0006_waiverplanning_oop_waiver_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airspacewaiver',
            name='timeframe',
            field=models.CharField(blank=True, help_text='Comma-separated timeframe codes selected for this operation.', max_length=100),
        ),
    ]
