# Generated by Django 4.2.20 on 2025-12-12 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('airspace', '0006_remove_waiverplanning_lighting_conditions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaiverApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Generated Description of Operations for this waiver.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='airspace.waiverplanning')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiver_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
