# Generated by Django 4.2.20 on 2025-12-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airspace', '0007_alter_airspacewaiver_timeframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='airspacewaiver',
            name='operation_activities',
            field=models.CharField(blank=True, help_text='Comma-separated activity codes describing what you are doing.', max_length=200),
        ),
        migrations.AddField(
            model_name='airspacewaiver',
            name='operation_activities_other',
            field=models.CharField(blank=True, help_text='Optional free-text description of the operation.', max_length=255),
        ),
    ]
