# Generated by Django 4.2.20 on 2025-12-12 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airspace', '0007_waiverapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiverplanning',
            name='airspace_class',
            field=models.CharField(blank=True, choices=[('B', 'Class B'), ('C', 'Class C'), ('D', 'Class D'), ('E', 'Class E'), ('G', 'Class G')], help_text='Class of airspace where operations will occur.', max_length=1),
        ),
    ]
