# Generated by Django 4.2.20 on 2025-12-12 03:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airspace', '0008_waiverplanning_airspace_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiverplanning',
            name='ground_environment_other',
            field=models.TextField(blank=True, help_text='Any additional ground environment types not covered by the checkbox list above (e.g., rail yards, marinas, etc.).'),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='ground_environment',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('residential', 'Residential property / housing'), ('commercial', 'Commercial buildings / business areas'), ('industrial', 'Industrial or construction sites'), ('agricultural', 'Agricultural land / open fields'), ('forested', 'Forested or rural terrain'), ('water', 'Water features (lakes, rivers, coastlines)'), ('roadways', 'Roadways / parking areas'), ('pedestrian', 'Pedestrian walkways / public access areas'), ('recreational', 'Recreational areas (parks, trails, fields)'), ('infrastructure', 'Critical infrastructure (utilities, towers, pipelines)'), ('unpopulated', 'Unpopulated or remote terrain'), ('crowd_sparse', 'Sparse people present'), ('crowd_moderate', 'Moderate public presence'), ('crowd_dense', 'Dense gatherings / event crowds')], max_length=50), blank=True, default=list, help_text='Types of ground environment present in the area.', size=None),
        ),
    ]
