# Generated by Django 4.2.20 on 2025-12-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airspace', '0008_airspacewaiver_operation_activities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airspacewaiver',
            name='aircraft_custom',
            field=models.CharField(blank=True, help_text='If not listed, enter the Manufacturer and Model.', max_length=255, verbose_name='Custom Aircraft'),
        ),
        migrations.AlterField(
            model_name='airspacewaiver',
            name='airspace_class',
            field=models.CharField(choices=[('B', 'Class B'), ('C', 'Class C'), ('D', 'Class D'), ('E', 'Class E'), ('G', 'Class G')], max_length=1, verbose_name='Airspace Class'),
        ),
        migrations.AlterField(
            model_name='airspacewaiver',
            name='lat_degrees',
            field=models.PositiveSmallIntegerField(verbose_name='Latitude Degrees'),
        ),
        migrations.AlterField(
            model_name='airspacewaiver',
            name='lat_direction',
            field=models.CharField(choices=[('N', 'N'), ('S', 'S')], max_length=1, verbose_name='Latitude Direction'),
        ),
        migrations.AlterField(
            model_name='airspacewaiver',
            name='lat_minutes',
            field=models.PositiveSmallIntegerField(verbose_name='Latitude Minutes'),
        ),
        migrations.AlterField(
            model_name='airspacewaiver',
            name='lat_seconds',
            field=models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Latitude Seconds'),
        ),
        migrations.AlterField(
            model_name='airspacewaiver',
            name='lon_degrees',
            field=models.PositiveSmallIntegerField(verbose_name='Longitude Degrees'),
        ),
        migrations.AlterField(
            model_name='airspacewaiver',
            name='lon_direction',
            field=models.CharField(choices=[('E', 'E'), ('W', 'W')], max_length=1, verbose_name='Longitude Direction'),
        ),
        migrations.AlterField(
            model_name='airspacewaiver',
            name='lon_minutes',
            field=models.PositiveSmallIntegerField(verbose_name='Longitude Minutes'),
        ),
        migrations.AlterField(
            model_name='airspacewaiver',
            name='lon_seconds',
            field=models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Longitude Seconds'),
        ),
        migrations.AlterField(
            model_name='airspacewaiver',
            name='max_agl',
            field=models.PositiveIntegerField(help_text='Maximum Altitude AGL in feet', verbose_name='Maximum Altitude (AGL)'),
        ),
        migrations.AlterField(
            model_name='airspacewaiver',
            name='nearest_airport',
            field=models.CharField(max_length=10, verbose_name='Nearest Airport (ICAO Code)'),
        ),
        migrations.AlterField(
            model_name='airspacewaiver',
            name='proposed_location',
            field=models.TextField(help_text='Venue name, address, GPS coordinates..', verbose_name='Location Description'),
        ),
        migrations.AlterField(
            model_name='airspacewaiver',
            name='related_waiver_details',
            field=models.CharField(blank=True, max_length=200, verbose_name='Related Waiver Number'),
        ),
        migrations.AlterField(
            model_name='airspacewaiver',
            name='short_description',
            field=models.TextField(verbose_name='Brief Description of Operations'),
        ),
    ]
