# Generated by Django 4.2.20 on 2025-12-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airspace', '0009_waiverplanning_ground_environment_other_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiverplanning',
            name='ground_environment_other',
            field=models.TextField(blank=True, help_text='Any additional ground environment types not covered by the checkbox list (e.g., rail yards, marinas, refineries, etc.).'),
        ),
    ]
