# Generated by Django 4.2.20 on 2025-12-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airspace', '0010_alter_waiverplanning_ground_environment_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiverplanning',
            name='generated_description_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
