# Generated by Django 4.2.20 on 2025-12-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airspace', '0011_waiverplanning_generated_description_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiverapplication',
            name='locked_description',
            field=models.BooleanField(default=False),
        ),
    ]
