# Generated by Django 4.2.20 on 2025-12-12 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airspace', '0012_waiverapplication_locked_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConopsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(db_index=True, max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField(blank=True)),
                ('locked', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conops_sections', to='airspace.waiverapplication')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('application', 'section_key')},
            },
        ),
    ]
