# Generated by Django 4.2.20 on 2025-12-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airspace', '0013_conopssection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conopssection',
            name='section_key',
            field=models.CharField(db_index=True, help_text="Internal identifier, e.g. 'purpose_of_operations'", max_length=50),
        ),
        migrations.AlterField(
            model_name='conopssection',
            name='title',
            field=models.CharField(help_text='Section title shown in the CONOPS document', max_length=150),
        ),
    ]
