# Generated by Django 4.2.20 on 2025-12-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airspace', '0014_alter_conopssection_section_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conopssection',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conopssection',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conopssection',
            name='section_key',
            field=models.SlugField(help_text="Internal identifier, e.g. 'purpose_of_operations'"),
        ),
        migrations.AlterField(
            model_name='conopssection',
            name='title',
            field=models.CharField(help_text='Section title shown in the CONOPS document', max_length=255),
        ),
    ]
