# Generated by Django 4.2.20 on 2025-12-15 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airspace', '0015_conopssection_is_complete_conopssection_validated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao', models.CharField(help_text='ICAO airport identifier (e.g. KIND)', max_length=4, unique=True)),
                ('name', models.CharField(help_text='Official airport name from FAA NASR', max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Airport Reference Point latitude (decimal degrees)', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Airport Reference Point longitude (decimal degrees)', max_digits=9)),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['icao'],
            },
        ),
    ]
