# Generated by Django 4.2.20 on 2025-12-15 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airspace', '0016_airport'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiverplanning',
            name='distance_to_airport_nm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Great-circle distance from operation location to nearest airport (NM).', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='waiverplanning',
            name='nearest_airport_ref',
            field=models.ForeignKey(blank=True, help_text='Airport reference selected from NASR (preferred).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiver_planning_entries', to='airspace.airport'),
        ),
    ]
