# Generated by Django 4.2.20 on 2025-12-16 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airspace', '0018_backfill_airport_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waiverplanning',
            options={},
        ),
    ]
