# Generated by Django 4.2.20 on 2025-12-16 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airspace', '0019_alter_waiverplanning_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waiverplanning',
            options={'ordering': ['-created_at'], 'verbose_name': 'Waiver Planning Entry', 'verbose_name_plural': 'Waiver Planning Entries'},
        ),
    ]
