# Generated by Django 4.2.20 on 2025-12-30 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airspace', '0020_alter_waiverplanning_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conopssection',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='conopssection',
            constraint=models.UniqueConstraint(fields=('application', 'section_key'), name='uniq_conopssection_app_sectionkey'),
        ),
    ]
