# Generated by Django 4.2.20 on 2026-01-18 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('airspace', '0021_alter_conopssection_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conopssection',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='conops_sections', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='conopssection',
            index=models.Index(fields=['user', 'application', 'section_key'], name='airspace_co_user_id_694443_idx'),
        ),
        migrations.AddIndex(
            model_name='waiverapplication',
            index=models.Index(fields=['user', '-created_at'], name='airspace_wa_user_id_33fde4_idx'),
        ),
        migrations.AddIndex(
            model_name='waiverplanning',
            index=models.Index(fields=['user', '-created_at'], name='airspace_wa_user_id_286c03_idx'),
        ),
    ]
