# Generated by Django 4.2.20 on 2026-01-23 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airspace', '0022_conopssection_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiverplanning',
            name='atc_checkin_procedure',
            field=models.TextField(blank=True, help_text='When/how you check-in, what info you provide, and termination procedure.'),
        ),
        migrations.AddField(
            model_name='waiverplanning',
            name='atc_coordination_method',
            field=models.CharField(blank=True, choices=[('phone', 'Phone'), ('radio', 'Radio'), ('both', 'Phone + Radio'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='waiverplanning',
            name='atc_deviation_triggers',
            field=models.TextField(blank=True, help_text='What triggers immediate termination or coordination (traffic, weather, etc.).'),
        ),
        migrations.AddField(
            model_name='waiverplanning',
            name='atc_facility_name',
            field=models.CharField(blank=True, help_text='Tower/TRACON/approach/airport ops facility name if known.', max_length=255),
        ),
        migrations.AddField(
            model_name='waiverplanning',
            name='atc_frequency',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='waiverplanning',
            name='atc_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='waiverplanning',
            name='containment_method',
            field=models.CharField(blank=True, choices=[('geofence', 'Geofence / max distance limit'), ('visual_markers', 'Visual boundary markers'), ('map_overlays', 'Map overlays / GPS reference points'), ('combination', 'Combination')], max_length=20),
        ),
        migrations.AddField(
            model_name='waiverplanning',
            name='containment_notes',
            field=models.TextField(blank=True, help_text='How boundaries are set, briefed, and verified on-site (no inventing).'),
        ),
        migrations.AddField(
            model_name='waiverplanning',
            name='corridor_length_ft',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waiverplanning',
            name='corridor_width_ft',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waiverplanning',
            name='crew_briefing_procedure',
            field=models.TextField(blank=True, help_text='Pre-ops briefing content: boundaries, roles, comms, abort triggers.'),
        ),
        migrations.AddField(
            model_name='waiverplanning',
            name='crew_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waiverplanning',
            name='flyaway_actions',
            field=models.TextField(blank=True, help_text='Immediate actions, tracking/last-known position capture, facility notification.'),
        ),
        migrations.AddField(
            model_name='waiverplanning',
            name='lost_link_actions',
            field=models.TextField(blank=True, help_text='Step-by-step actions: what happens, who calls whom, how ops terminate.'),
        ),
        migrations.AddField(
            model_name='waiverplanning',
            name='lost_link_behavior',
            field=models.CharField(blank=True, choices=[('rth', 'Return-to-Home (RTH)'), ('hover', 'Hover in place'), ('land', 'Land immediately')], max_length=20),
        ),
        migrations.AddField(
            model_name='waiverplanning',
            name='max_groundspeed_mph',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waiverplanning',
            name='max_wind_mph',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waiverplanning',
            name='min_visibility_sm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='waiverplanning',
            name='operation_area_type',
            field=models.CharField(choices=[('radius', 'Radius (circular area)'), ('corridor', 'Corridor (linear operations)'), ('polygon', 'Polygon (defined boundary)'), ('site', 'Single site / venue footprint')], default='radius', max_length=20),
        ),
        migrations.AddField(
            model_name='waiverplanning',
            name='radio_discipline',
            field=models.CharField(blank=True, choices=[('sterile', 'Sterile comms during flight'), ('standard', 'Standard comms')], max_length=20),
        ),
        migrations.AddField(
            model_name='waiverplanning',
            name='rth_altitude_ft_agl',
            field=models.PositiveIntegerField(blank=True, help_text='If using RTH, the programmed RTH altitude in feet AGL.', null=True),
        ),
        migrations.AddField(
            model_name='waiverplanning',
            name='weather_go_nogo',
            field=models.TextField(blank=True, help_text='Any additional go/no-go rules (gust spread, precip, ceiling, lightning).'),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='safety_features_notes',
            field=models.TextField(blank=True, help_text='Key safety features, redundancies, or geofencing used for this operation.If a drone with a safety profile is selected, this will be auto-filled.'),
        ),
    ]
