# Generated by Django 4.2.20 on 2026-01-23 02:02

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_droneincidentreport_user_generaldocument_user_and_more'),
        ('equipment', '0008_equipment_user_alter_dronesafetyprofile_active_and_more'),
        ('pilot', '0003_training_user'),
        ('airspace', '0023_waiverplanning_atc_checkin_procedure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiverplanning',
            name='aircraft',
            field=models.ForeignKey(blank=True, limit_choices_to={'equipment_type': 'Drone'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiver_planning_entries', to='equipment.equipment'),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='aircraft_count',
            field=models.CharField(blank=True, choices=[('single', 'Single aircraft'), ('multi_sequential', 'Multiple aircraft (sequential use)'), ('multi_simultaneous', 'Multiple aircraft (simultaneous use)')], max_length=25),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='airspace_class',
            field=models.CharField(blank=True, choices=[('B', 'Class B'), ('C', 'Class C'), ('D', 'Class D'), ('E', 'Class E'), ('G', 'Class G')], max_length=1),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='atc_checkin_procedure',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='atc_deviation_triggers',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='atc_facility_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='containment_method',
            field=models.CharField(blank=True, choices=[('geofence', 'Geofence'), ('visual_markers', 'Visual markers'), ('map_overlays', 'Map overlays'), ('combination', 'Combination')], max_length=20),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='containment_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='crew_briefing_procedure',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='distance_to_airport_nm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='estimated_crowd_size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='flight_duration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='flights_per_day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='flyaway_actions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='ground_environment',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('residential', 'Residential property / housing'), ('commercial', 'Commercial buildings / business areas'), ('industrial', 'Industrial or construction sites'), ('agricultural', 'Agricultural land / open fields'), ('forested', 'Forested or rural terrain'), ('water', 'Water features (lakes, rivers, coastlines)'), ('roadways', 'Roadways / parking areas'), ('pedestrian', 'Pedestrian walkways / public access areas'), ('recreational', 'Recreational areas (parks, trails, fields)'), ('infrastructure', 'Critical infrastructure (utilities, towers, pipelines)'), ('unpopulated', 'Unpopulated or remote terrain'), ('crowd_sparse', 'Sparse people present'), ('crowd_moderate', 'Moderate public presence'), ('crowd_dense', 'Dense gatherings / event crowds')], max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='ground_environment_other',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='has_visual_observer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='insurance_coverage_limit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='launch_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='location_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='location_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='location_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='location_radius',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='location_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='lost_link_actions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='lost_link_behavior',
            field=models.CharField(blank=True, choices=[('rth', 'RTH'), ('hover', 'Hover'), ('land', 'Land')], max_length=20),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='mv_waiver_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mv_waiver_planning_entries', to='documents.generaldocument'),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='mv_waiver_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='nearest_airport',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='nearest_airport_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiver_planning_entries', to='airspace.airport'),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='oop_waiver_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oop_waiver_planning_entries', to='documents.generaldocument'),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='oop_waiver_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='operates_under_107145',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='operates_under_10739',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='operation_area_type',
            field=models.CharField(choices=[('radius', 'Radius'), ('corridor', 'Corridor'), ('polygon', 'Polygon'), ('site', 'Site')], default='radius', max_length=20),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='pilot_cert_manual',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='pilot_flight_hours',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Approximate total UAS flight hours.', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='pilot_name_manual',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='pilot_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiver_planning_entries', to='pilot.pilotprofile'),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='prepared_procedures',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('preflight', 'Pre-flight checklist used'), ('postflight', 'Post-flight checklist used'), ('lost_link', 'Lost-link / flyaway procedure in place'), ('emergency_lz', 'Emergency landing zones pre-identified')], max_length=30), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='purpose_operations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('event_filming', 'Event filming / broadcast'), ('pro_photography', 'Professional aerial photography'), ('mapping_survey', 'Mapping / survey'), ('infrastructure_inspection', 'Infrastructure inspection'), ('public_safety', 'Public safety / incident support'), ('training_proficiency', 'Training / proficiency flights'), ('real_estate', 'Real estate photography')], max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='purpose_operations_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='radio_discipline',
            field=models.CharField(blank=True, choices=[('sterile', 'Sterile'), ('standard', 'Standard')], max_length=20),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='safety_features_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='street_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='uses_drone_detection',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='uses_flight_tracking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='venue_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='weather_go_nogo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='waiverplanning',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
