# Generated by Django 4.2.20 on 2025-12-02 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pilotprofile',
            table='app_pilotprofile',
        ),
        migrations.AlterModelTable(
            name='training',
            table='app_training',
        ),
    ]
