# Generated by Django 4.2.20 on 2026-01-13 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pilot', '0002_alter_pilotprofile_table_alter_training_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
