# Generated by Django 4.2.20 on 2025-11-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DroneIncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('reported_by', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('location', models.CharField(max_length=200)),
                ('event_type', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('injuries', models.BooleanField(default=False)),
                ('injury_details', models.TextField(blank=True)),
                ('damage', models.BooleanField(default=False)),
                ('damage_cost', models.CharField(blank=True, max_length=100)),
                ('damage_desc', models.TextField(blank=True)),
                ('drone_model', models.CharField(max_length=100)),
                ('registration', models.CharField(max_length=100)),
                ('controller', models.CharField(max_length=100)),
                ('payload', models.CharField(max_length=100)),
                ('battery', models.CharField(max_length=50)),
                ('weather', models.CharField(max_length=100)),
                ('wind', models.CharField(max_length=50)),
                ('temperature', models.CharField(max_length=50)),
                ('lighting', models.CharField(max_length=100)),
                ('witnesses', models.BooleanField(default=False)),
                ('witness_details', models.TextField(blank=True)),
                ('emergency', models.BooleanField(default=False)),
                ('agency_response', models.TextField(blank=True)),
                ('scene_action', models.TextField(blank=True)),
                ('faa_report', models.BooleanField(default=False)),
                ('faa_ref', models.CharField(blank=True, max_length=100)),
                ('cause', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('signature', models.CharField(max_length=100)),
                ('sign_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='GeneralDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Insurance', 'Insurance'), ('FAA', 'FAA Waivers'), ('Registrations', 'Drone Registrations'), ('event', 'Event Instructions'), ('Policies', 'Policies'), ('Compliance', 'Compliance'), ('Legal', 'Legal'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='general_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SOPDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='sop_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
