# Generated by Django 4.2.20 on 2025-12-02 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='droneincidentreport',
            options={'ordering': ['-report_date']},
        ),
        migrations.AlterModelOptions(
            name='generaldocument',
            options={'ordering': ['-title']},
        ),
        migrations.AlterModelOptions(
            name='sopdocument',
            options={'ordering': ['-title']},
        ),
        migrations.AlterModelTable(
            name='droneincidentreport',
            table='flightplan_droneincidentreport',
        ),
        migrations.AlterModelTable(
            name='generaldocument',
            table='flightplan_generaldocument',
        ),
        migrations.AlterModelTable(
            name='sopdocument',
            table='flightplan_sopdocument',
        ),
    ]
