# Generated by Django 4.2.20 on 2025-12-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_droneincidentreport_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaldocument',
            name='category',
            field=models.CharField(choices=[('Insurance', 'Insurance'), ('FAA Airspace Waivers', 'FAA Airspace Waivers'), ('FAA Operational Waivers', 'FAA Operational Waivers'), ('Registrations', 'Drone Registrations'), ('event', 'Event Instructions'), ('Policies', 'Policies'), ('Compliance', 'Compliance'), ('Legal', 'Legal'), ('Other', 'Other'), ('FAA Airspace Waivers', 'FAA Airspace Waivers')], max_length=50),
        ),
    ]
