# Generated by Django 4.2.20 on 2026-01-11 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0004_alter_generaldocument_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='droneincidentreport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drone_incident_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generaldocument',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sopdocument',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sop_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
