# Generated by Django 4.2.20 on 2025-12-02 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='opsplan',
            new_name='flightplan__event_i_472452_idx',
            old_name='operations__event_i_e19acc_idx',
        ),
        migrations.RenameIndex(
            model_name='opsplan',
            new_name='flightplan__event_i_3b45e0_idx',
            old_name='operations__event_i_1f4947_idx',
        ),
        migrations.RenameIndex(
            model_name='opsplan',
            new_name='flightplan__status_fde9fe_idx',
            old_name='operations__status_6dcbe6_idx',
        ),
        migrations.RenameIndex(
            model_name='opsplan',
            new_name='flightplan__updated_246d03_idx',
            old_name='operations__updated_1c0a52_idx',
        ),
        migrations.RenameIndex(
            model_name='opsplan',
            new_name='flightplan__approve_461ace_idx',
            old_name='operations__approve_0a892d_idx',
        ),
        migrations.AlterModelTable(
            name='opsplan',
            table='flightplan_opsplan',
        ),
    ]
